apiVersion: apps/v1
kind: Deployment
metadata:
    name: hotrod-deployment
    labels:
        app: hotrod
spec:
    replicas: 1
    selector:
        matchLabels:
            app: hotrod
    template:
        metadata:
            labels:
                app: hotrod
        spec:
            containers:
              - name: hotrod
                image: jaegertracing/example-hotrod:latest
                ports:
                 - containerPort: 8080
                   name: port1
              - name: jaeger-agent
                image: jaegertracing/jaeger-agent
                ports:
                  - containerPort: 5775
                    protocol: UDP
                  - containerPort: 5778
                  - containerPort: 6831
                    protocol: UDP
                  - containerPort: 6832
                    protocol: UDP
             
                command:
                  - "/go/bin/agent-linux"
                  - "--collector.host-port=jaeger-collector.default.svc:14267"
              - name: hw
                image: karthequian/helloworld:latest
---
apiVersion: v1
kind: Service
metadata:
    name: hotrod-service
    namespace: default
spec:
    type: NodePort
    selector:
        app: hotrod
    ports:
      - name: hotrod-port
        protocol: TCP
        port: 8080

    

