apiVersion: apps/v1
kind: Deployment
metadata:
    name: wishlist-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: wishlist
    template:
        metadata:
            labels:
                app: wishlist
        spec:
            volumes:
              - name: config-volume
                configMap:
                    name: log-config
              - name: secret-volume
                secret:
                  secretName: mysql-connection-secret
            containers:
              - name: wishlist
                image: karthequian/wishlist:1.0
                ports:
                  - containerPort: 8080
                env:
                  - name: PORT
                    value: "8080"
                  - name: LOG_LEVEL
                    valueFrom:
                        configMapKeyRef:
                            name: log-config
                            key: log-level
                livenessProbe:
                    httpGet:
                        path: /status
                        port: 8080
                    initialDelaySeconds: 5
                    timeoutSeconds: 1
              - name: catelog
                image: karthequian/wishlist-catalog:1.0
                ports:
                  - containerPort: 8081
                env:
                  - name: PORT
                    value: "8081"
                livenessProbe:
                    httpGet:
                        path: /status
                        port: 8080
                    initialDelaySeconds: 5
                    timeoutSeconds: 1
              - name: auth
                image: karthequian/wishlist-auth:1.0
                ports:
                  - containerPort: 8082
                volumeMounts:
                    - mountPath: "/etc/mysq-volume"
                      name: secret-volume
                      readOnly: true
                env:
                  - name: PORT
                    value: "8082"
                  - name: MYSQL_CONNECTION_STRING
                    valueFrom:
                      secretKeyRef:
                          key: connection-string
                          name: mysql-connection-secret
                livenessProbe:
                    httpGet:
                        path: /status
                        port: 8080
                    initialDelaySeconds: 5
                    timeoutSeconds: 1


---
kind: Service
apiVersion: v1
metadata:
    name: wishlist-service
spec:
    type: NodePort
    selector:
        app: wishlist
    ports:
      - name: wishlist-port
        protocol: TCP
        port: 8080
      - name: wishlist-catelog-port
        protocol: TCP
        port: 8081
      - name: wishlist-auth-port
        protocol: TCP
        port: 8082
